### ISSUE TITLE
when make ,the output give errors?

### ISSUE THREAD

**Issue by yinxx** [Ohyoukillkenny/riscv-simulator#1]
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::s_type_opcode_process(uint32_t)’:
/data/riscv-simulator/cpu/cpu.cpp:245:18: error: ‘bitset’ is not a member of ‘std’
             std::bitset<32> y(funct3);
                  ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:245:18: note: suggested alternative: ‘bit_not’
             std::bitset<32> y(funct3);
                  ^~~~~~
                  bit_not
/data/riscv-simulator/cpu/cpu.cpp:245:29: error: ‘y’ was not declared in this scope
             std::bitset<32> y(funct3);
                             ^
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::l_type_opcode_process(uint32_t)’:
/data/riscv-simulator/cpu/cpu.cpp:301:18: error: ‘bitset’ is not a member of ‘std’
             std::bitset<32> y(funct3);
                  ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:301:18: note: suggested alternative: ‘bit_not’
             std::bitset<32> y(funct3);
                  ^~~~~~
                  bit_not
/data/riscv-simulator/cpu/cpu.cpp:301:29: error: ‘y’ was not declared in this scope
             std::bitset<32> y(funct3);
                             ^
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::b_type_opcode_process(uint32_t)’:
/data/riscv-simulator/cpu/cpu.cpp:366:18: error: ‘bitset’ is not a member of ‘std’
             std::bitset<32> y(funct3);
                  ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:366:18: note: suggested alternative: ‘bit_not’
             std::bitset<32> y(funct3);
                  ^~~~~~
                  bit_not
/data/riscv-simulator/cpu/cpu.cpp:366:29: error: ‘y’ was not declared in this scope
             std::bitset<32> y(funct3);
                             ^
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::process_instr(uint32_t)’:
/data/riscv-simulator/cpu/cpu.cpp:460:18: error: ‘bitset’ is not a member of ‘std’
             std::bitset<32> y(opcode);
                  ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:460:18: note: suggested alternative: ‘bit_not’
             std::bitset<32> y(opcode);
                  ^~~~~~
                  bit_not
/data/riscv-simulator/cpu/cpu.cpp:460:29: error: ‘y’ was not declared in this scope
             std::bitset<32> y(opcode);
                             ^
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::run_debug()’:
/data/riscv-simulator/cpu/cpu.cpp:476:14: error: ‘bitset’ is not a member of ‘std’
         std::bitset<32> y(instr);
              ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:476:14: note: suggested alternative: ‘bit_not’
         std::bitset<32> y(instr);
              ^~~~~~
              bit_not
/data/riscv-simulator/cpu/cpu.cpp:476:25: error: ‘y’ was not declared in this scope
         std::bitset<32> y(instr);
                         ^
/data/riscv-simulator/cpu/cpu.cpp: In member function ‘void cpu::print()’:
/data/riscv-simulator/cpu/cpu.cpp:504:18: error: ‘bitset’ is not a member of ‘std’
             std::bitset<32> bin(cpu_regs -> get_reg(i));
                  ^~~~~~
/data/riscv-simulator/cpu/cpu.cpp:504:18: note: suggested alternative: ‘bit_not’
             std::bitset<32> bin(cpu_regs -> get_reg(i));
                  ^~~~~~
                  bit_not
/data/riscv-simulator/cpu/cpu.cpp:504:29: error: ‘bin’ was not declared in this scope
             std::bitset<32> bin(cpu_regs -> get_reg(i));
                             ^~~
make[2]: *** [CMakeFiles/TestAll.dir/build.make:102: CMakeFiles/TestAll.dir/cpu/cpu.cpp.o] Error 1
make[2]: Leaving directory '/data/riscv-simulator'
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/TestAll.dir/all] Error 2
make[1]: Leaving directory '/data/riscv-simulator'
make: *** [Makefile:84: all] Error 2

**Comment by Ohyoukillkenny** [comment]
Bug fixed.
Needs to import bitset by explicitly writing "#include<bitset>" with CMake.
